/* auto-generated from cheat.js — do not edit */
#ifndef WARRIOR_CHEAT_JS_H
#define WARRIOR_CHEAT_JS_H
static const char *kCheatJS =
  "/**\n"
  " *  Warrior 1.0.4 修改脚本（cocos creator 2.4.11 / V8）\n"
  " *  注入时机：hook ScriptEngine::onGetStringFromFile(0x101158fd4)，读 main.js 后 evalString 本脚本\n"
  " *  运行前提：window.$fc / $fc.battleMgr.bBl 由游戏自身创建\n"
  " */\n"
  "(function () {\n"
  "  if (window.__WARRIOR_CHEAT__) return;\n"
  "\n"
  "  var C = {\n"
  "    version: '1.0.0',\n"
  "    kill: false,      // 秒杀\n"
  "    god: false,       // 无敌\n"
  "    speed: 1.0,       // 移动速度倍率\n"
  "    _speedPatched: false,\n"
  "    _godApplied: false,\n"
  "    _lastErr: ''\n"
  "  };\n"
  "  window.__WARRIOR_CHEAT__ = C;\n"
  "\n"
  "  /* ---------- 基础访问器（全部空安全） ---------- */\n"
  "  function FC() { try { return window.$fc || null; } catch (e) { return null; } }\n"
  "  function battleInst() {\n"
  "    try { var f = FC(); return (f && f.battleMgr && f.battleMgr.bBl) ? f.battleMgr.bBl : null; }\n"
  "    catch (e) { return null; }\n"
  "  }\n"
  "  function ctx() { var b = battleInst(); try { return (b && b.ne) ? b.ne : null; } catch (e) { return null; } }\n"
  "  function units() {\n"
  "    var c = ctx(); if (!c) return [];\n"
  "    try { return (c.fu && c.fu.bkN) ? c.fu.bkN : []; } catch (e) { return []; }\n"
  "  }\n"
  "  function me() { var c = ctx(); try { return (c && c.nx) ? c.nx : null; } catch (e) { return null; } }\n"
  "  function myCamp() { var m = me(); try { return (m && m.hD) ? m.hD.biI : -1; } catch (e) { return -1; } }\n"
  "  function campOf(e) { try { return (e && e.hD) ? e.hD.biI : null; } catch (err) { return null; } }\n"
  "\n"
  "  /* ---------- 属性枚举（实测 AttributeTableEnum） ---------- */\n"
  "  var ATTR = { hpMax: 5, ap: 7, sp: 8, atkSpeed: 20, speed: 22, finalDamageRed: 36 };\n"
  "  var BIG_HP = 3147483648;\n"
  "  var MAX_RED = 1e4;\n"
  "\n"
  "  /* ---------- 移速：重定义 beZ getter（返回 GameAttriTableEnum.speed） ---------- */\n"
  "  function patchSpeed() {\n"
  "    if (C._speedPatched) return;\n"
  "    var u = units(); if (!u.length) return;\n"
  "    var proto = Object.getPrototypeOf(u[0]);\n"
  "    while (proto) {\n"
  "      var d = null;\n"
  "      try { d = Object.getOwnPropertyDescriptor(proto, 'beZ'); } catch (e) {}\n"
  "      if (d && typeof d.get === 'function') {\n"
  "        var orig = d.get;\n"
  "        Object.defineProperty(proto, 'beZ', {\n"
  "          configurable: true,\n"
  "          enumerable: !!d.enumerable,\n"
  "          get: function () { return orig.call(this) * (C.speed || 1); }\n"
  "        });\n"
  "        C._speedPatched = true;\n"
  "        return;\n"
  "      }\n"
  "      proto = Object.getPrototypeOf(proto);\n"
  "    }\n"
  "  }\n"
  "\n"
  "  /* ---------- 无敌：完全复刻游戏内置 GM 命令 H($ug.H) 的数值模板 ---------- */\n"
  "  function godOn(e) {\n"
  "    var hv = e.hv; if (!hv) return;\n"
  "    if (typeof hv.beJ === 'function') {\n"
  "      hv.beJ(ATTR.hpMax, BIG_HP);\n"
  "      hv.beJ(ATTR.ap, 1e5);\n"
  "      hv.beJ(ATTR.sp, 1e5);\n"
  "      hv.beJ(ATTR.speed, 15000);\n"
  "      hv.beJ(ATTR.atkSpeed, 1e4);\n"
  "      hv.beJ(ATTR.finalDamageRed, MAX_RED);\n"
  "    }\n"
  "    try { hv.beu = hv.bev; } catch (err) {}\n"
  "    try { hv.beD = 1; } catch (err) {}      // 死亡时自动回满（游戏内建机制）\n"
  "    e.__wg = true;\n"
  "  }\n"
  "  function godOff(e) {\n"
  "    var hv = e.hv; if (!hv) return;\n"
  "    if (typeof hv.beK === 'function') {\n"
  "      hv.beK(ATTR.hpMax, BIG_HP);\n"
  "      hv.beK(ATTR.ap, 1e5);\n"
  "      hv.beK(ATTR.sp, 1e5);\n"
  "      hv.beK(ATTR.speed, 15000);\n"
  "      hv.beK(ATTR.atkSpeed, 1e4);\n"
  "      hv.beK(ATTR.finalDamageRed, MAX_RED);\n"
  "    }\n"
  "    try { hv.beD = 0; } catch (err) {}\n"
  "    e.__wg = false;\n"
  "  }\n"
  "\n"
  "  function applyGod() {\n"
  "    var mc = myCamp();\n"
  "    if (mc < 0) return;\n"
  "    var list = units();\n"
  "    for (var i = 0; i < list.length; i++) {\n"
  "      var e = list[i];\n"
  "      try {\n"
  "        if (!e || !e.hv) continue;\n"
  "        if (campOf(e) !== mc) continue;           // 只作用于己方阵营\n"
  "        if (C.god) {\n"
  "          if (!e.__wg) godOn(e);\n"
  "          if (e.hv.beu < e.hv.bev) e.hv.beu = e.hv.bev;   // 持续满血\n"
  "        } else if (e.__wg) {\n"
  "          godOff(e);\n"
  "        }\n"
  "      } catch (err) {}\n"
  "    }\n"
  "    C._godApplied = C.god;\n"
  "  }\n"
  "\n"
  "  /* ---------- 秒杀：对敌方调用实体受击函数 hX(attacker, damage=目标当前HP) ---------- */\n"
  "  function applyKill() {\n"
  "    var m = me(); if (!m) return;\n"
  "    var mc = myCamp();\n"
  "    var list = units();\n"
  "    for (var i = 0; i < list.length; i++) {\n"
  "      var e = list[i];\n"
  "      try {\n"
  "        if (!e || !e.hv || e === m) continue;\n"
  "        if (campOf(e) === mc) continue;           // 只打敌方\n"
  "        if (!(e.hv.beu > 0)) continue;\n"
  "        if (typeof e.hX === 'function') {\n"
  "          e.hX(m, e.hv.beu, null);                // 伤害 = 目标满血 → 一击必杀\n"
  "        } else {\n"
  "          e.hv.beu = 0;                           // 兜底：直接置 0\n"
  "        }\n"
  "      } catch (err) { C._lastErr = '' + err; }\n"
  "    }\n"
  "  }\n"
  "\n"
  "  /* ---------- 主循环 ---------- */\n"
  "  function tick() {\n"
  "    try {\n"
  "      if (!ctx()) return;\n"
  "      if (C.speed && C.speed !== 1) patchSpeed();\n"
  "      applyGod();\n"
  "      if (C.kill) applyKill();\n"
  "    } catch (e) { C._lastErr = '' + e; }\n"
  "  }\n"
  "  setInterval(tick, 120);\n"
  "\n"
  "  /* ---------- 原生面板桥 ---------- */\n"
  "  C.set = function (k, v) {\n"
  "    if (k === 'speed') { C.speed = Number(v) || 1.0; return C.speed; }\n"
  "    C[k] = !!v;\n"
  "    if (k === 'god' && !v) applyGod();   // 立刻还原\n"
  "    return C[k];\n"
  "  };\n"
  "  C.status = function () {\n"
  "    return JSON.stringify({ kill: C.kill, god: C.god, speed: C.speed, err: C._lastErr });\n"
  "  };\n"
  "  window.warriorCheatSet = C.set;\n"
  "  window.warriorCheatStatus = C.status;\n"
  "\n"
  "  try { console.log('[WARRIOR] cheat v' + C.version + ' loaded, waiting for $fc ...'); } catch (e) {}\n"
  "})();\n"
  "\n"
  ;
#endif
