/* auto-generated from cheat.js — do not edit */
#ifndef WARRIOR_CHEAT_JS_H
#define WARRIOR_CHEAT_JS_H
static const char *kCheatJS =
  "/**\n"
  " *  Warrior 1.0.4 修改脚本 v1.0.9\n"
  " *\n"
  " *  ★ 关键发现（v1.0.8 日志）：\n"
  " *      [ENV:speed] fc=N bBl=N nb=N ne=N nx=N\n"
  " *    ⇒ 注入时游戏全局 $fc **尚未创建**（注入时机早于游戏主体初始化）。\n"
  " *      我的代码在 fc 不存在时直接 return，并未操作任何游戏对象。\n"
  " *\n"
  " *  ★ v1.0.9 改动：\n"
  " *    1) 加载后**等待 $fc / cc 就绪**，就绪前不做任何游戏对象操作\n"
  " *    2) 等待机制优先级：cc.director 事件 → setInterval → 原生 pump(warriorTick)\n"
  " *    3) 暴露 window.warriorTick() 供原生侧低频推动（双保险）\n"
  " *    4) 日志改为**内存缓冲 + 每 8 条落盘一次**（IO 降低 ~90%，排除 IO 因素）\n"
  " *    5) 上下文探测：打印 window/globalThis/cc/jsb 类型，确认执行上下文\n"
  " */\n"
  "(function () {\n"
  "  if (window.__WARRIOR_CHEAT__) return;\n"
  "\n"
  "  var C = {\n"
  "    version: '1.0.9',\n"
  "    kill: false, god: false, auto: false,\n"
  "    speed: 1.0,\n"
  "    ready: false,\n"
  "    err: '', _errN: 0,\n"
  "    _spd: null,\n"
  "    _timer: null,\n"
  "    _tickN: 0,\n"
  "    _pumpN: 0,\n"
  "    _buf: []\n"
  "  };\n"
  "  window.__WARRIOR_CHEAT__ = C;\n"
  "\n"
  "  /* ---------------- 日志：内存缓冲 + 批量落盘 ---------------- */\n"
  "  function flush() {\n"
  "    if (!C._buf.length) return;\n"
  "    var s = C._buf.join('\\n');\n"
  "    C._buf = [];\n"
  "    try {\n"
  "      var fu = (typeof jsb !== 'undefined') && jsb.fileUtils;\n"
  "      if (!fu || typeof fu.writeStringToFile !== 'function') return;\n"
  "      var p = (window.__WR_PATH__ || '') + 'warrior_dbg.txt';\n"
  "      var old = (typeof fu.getStringFromFile === 'function') ? (fu.getStringFromFile(p) || '') : '';\n"
  "      fu.writeStringToFile((old + s + '\\n').slice(-8000), p);   // 内容在前\n"
  "    } catch (x) {}\n"
  "  }\n"
  "  function log(s) {\n"
  "    C._buf.push(s);\n"
  "    if (C._buf.length >= 8) flush();\n"
  "  }\n"
  "  function logNow(s) { C._buf.push(s); flush(); }\n"
  "  function fail(where, e) {\n"
  "    if (C._errN++ > 20) return;\n"
  "    C.err = where + ': ' + ((e && e.message) ? e.message : String(e));\n"
  "    logNow('[ERR] ' + C.err);\n"
  "  }\n"
  "\n"
  "  /* ---------------- 上下文探测（只做一次） ---------------- */\n"
  "  function probeContext() {\n"
  "    var s = [];\n"
  "    s.push('win=' + (typeof window));\n"
  "    s.push('gthis=' + (typeof globalThis));\n"
  "    try { s.push('same=' + (window === globalThis)); } catch (e) { s.push('same=?'); }\n"
  "    s.push('cc=' + (typeof cc));\n"
  "    s.push('jsb=' + (typeof jsb));\n"
  "    try { s.push('wkeys=' + (window ? Object.keys(window).length : -1)); } catch (e) { s.push('wkeys=?'); }\n"
  "    try { s.push('hasFC=' + (window.$fc ? 'Y' : 'N')); } catch (e) { s.push('hasFC=?'); }\n"
  "    logNow('[CTX] ' + s.join(' '));\n"
  "  }\n"
  "\n"
  "  /* ---------------- 就绪判定 ---------------- */\n"
  "  function FC()  { try { return window.$fc || null; } catch (e) { return null; } }\n"
  "  function BBl() { try { var f = FC(); return (f && f.battleMgr && f.battleMgr.bBl) ? f.battleMgr.bBl : null; } catch (e) { return null; } }\n"
  "  function NB()  { try { var b = BBl(); return (b && b.nb) ? b.nb : null; } catch (e) { return null; } }\n"
  "  function CTX() { try { var b = BBl(); return (b && b.ne) ? b.ne : null; } catch (e) { return null; } }\n"
  "  function ME()  { try { var c = CTX(); return (c && c.nx) ? c.nx : null; } catch (e) { return null; } }\n"
  "  function inBattle() {\n"
  "    try {\n"
  "      var b = BBl(); if (!b) return false;\n"
  "      if (typeof b.nl === 'function') return !!b.nl();\n"
  "    } catch (e) {}\n"
  "    return !!CTX();\n"
  "  }\n"
  "  function CAMP() { try { var m = ME(); return (m && m.hD) ? m.hD.biI : -1; } catch (e) { return -1; } }\n"
  "  function UNITS() {\n"
  "    try {\n"
  "      var c = CTX(); if (!c || !c.fu) return null;\n"
  "      var arr = c.fu.bkN;\n"
  "      return (arr && typeof arr.length === 'number') ? arr : null;\n"
  "    } catch (e) { fail('units', e); return null; }\n"
  "  }\n"
  "  function campOf(e) { try { return (e && e.hD) ? e.hD.biI : null; } catch (x) { return null; } }\n"
  "\n"
  "  // 游戏根对象是否就绪（battleMgr 存在即认为可工作）\n"
  "  function gameReady() { return !!BBl(); }\n"
  "\n"
  "  /* ---------------- 功能（全部一次性、极保守） ---------------- */\n"
  "  function doGod() {\n"
  "    var nb = NB();\n"
  "    if (!nb || typeof nb.bAj !== 'function') { log('[SKIP] god: nb.bAj missing'); return false; }\n"
  "    try { nb.bAj(); logNow('[OK] god pushed'); return true; }\n"
  "    catch (e) { fail('doGod', e); return false; }\n"
  "  }\n"
  "  function doKill() {\n"
  "    var nb = NB();\n"
  "    if (!nb || typeof nb.bAk !== 'function') { log('[SKIP] kill: nb.bAk missing'); return false; }\n"
  "    try { nb.bAk(); logNow('[OK] kill pushed'); return true; }\n"
  "    catch (e) { fail('doKill', e); return false; }\n"
  "  }\n"
  "  var A_SPEED = 22;\n"
  "  function doSpeed() {\n"
  "    if (!C._spd) { try { C._spd = new WeakMap(); } catch (e) { fail('WeakMap', e); return false; } }\n"
  "    var mc = CAMP(); if (mc < 0) { log('[SKIP] speed: camp<0'); return false; }\n"
  "    var list = UNITS(); if (!list) { log('[SKIP] speed: units null'); return false; }\n"
  "    var mult = C.speed || 1, n = 0;\n"
  "    for (var i = 0; i < list.length; i++) {\n"
  "      var e = list[i];\n"
  "      try {\n"
  "        if (!e || !e.hv) continue;\n"
  "        if (campOf(e) !== mc) continue;\n"
  "        var hv = e.hv;\n"
  "        if (typeof hv.beI !== 'function' || typeof hv.beJ !== 'function') continue;\n"
  "        var cur = hv.beI(A_SPEED);\n"
  "        if (typeof cur !== 'number' || !isFinite(cur)) continue;\n"
  "        var applied = C._spd.get(hv) || 0;\n"
  "        var base = cur - applied;\n"
  "        if (!(base > 0)) continue;\n"
  "        var delta = Math.round(base * mult) - cur;\n"
  "        if (delta !== 0) { hv.beJ(A_SPEED, delta); C._spd.set(hv, applied + delta); n++; }\n"
  "      } catch (err) { fail('speed item', err); }\n"
  "    }\n"
  "    logNow('[OK] speed x' + mult + ' -> ' + n + ' units');\n"
  "    return true;\n"
  "  }\n"
  "\n"
  "  /* ---------------- 每帧/周期任务 ---------------- */\n"
  "  function onFrame(src) {\n"
  "    C._tickN++;\n"
  "    try {\n"
  "      if (!gameReady()) {\n"
  "        // 每 ~2 秒报一次等待状态\n"
  "        if (C._tickN % 10 === 1) log('[..] waiting game: tick#' + C._tickN + ' src=' + src +\n"
  "                                     ' fc=' + (FC() ? 'Y' : 'N'));\n"
  "        return;\n"
  "      }\n"
  "      if (!C.ready) {\n"
  "        C.ready = true;\n"
  "        logNow('[OK] game ready! bBl=' + (BBl() ? 'Y' : 'N') + ' nb=' + (NB() ? 'Y' : 'N') +\n"
  "               ' src=' + src + ' tick#' + C._tickN);\n"
  "      }\n"
  "      if (!C.auto) return;                 // 未开\"自动\"时，只响应按钮\n"
  "      if (!inBattle()) return;\n"
  "      if (C.god)  doGod();\n"
  "      if (C.kill) doKill();\n"
  "      if (C.speed > 1) doSpeed();\n"
  "    } catch (e) { fail('onFrame', e); }\n"
  "  }\n"
  "\n"
  "  /* ---------------- 驱动（多重兜底） ---------------- */\n"
  "  function startDriver() {\n"
  "    if (C._timer || C._drvEvent) return;\n"
  "    // 1) cocos 事件（最可靠，引擎自带逐帧派发）\n"
  "    try {\n"
  "      if (typeof cc !== 'undefined' && cc.director && cc.Director) {\n"
  "        var EV = cc.Director.EVENT_AFTER_UPDATE;\n"
  "        if (EV) {\n"
  "          cc.director.on(EV, function () { onFrame('evt'); });\n"
  "          C._drvEvent = true;\n"
  "          logNow('[OK] driver=cc.director.EVENT_AFTER_UPDATE');\n"
  "          return;\n"
  "        }\n"
  "      }\n"
  "    } catch (e) { log('[..] cc event driver fail: ' + e); }\n"
  "    // 2) setInterval\n"
  "    try {\n"
  "      C._timer = setInterval(function () { onFrame('timer'); }, 250);\n"
  "      logNow('[OK] driver=setInterval id=' + C._timer);\n"
  "      return;\n"
  "    } catch (e) { log('[..] setInterval fail: ' + e); }\n"
  "    logNow('[!!] no driver available (waiting for native pump)');\n"
  "  }\n"
  "\n"
  "  // 原生侧低频 pump 会调用它\n"
  "  window.warriorTick = function () { C._pumpN++; onFrame('pump'); };\n"
  "\n"
  "  /* ---------------- 面板桥 ---------------- */\n"
  "  C.set = function (k, v) {\n"
  "    try {\n"
  "      if (k === 'speed') {\n"
  "        C.speed = Number(v) || 1.0;\n"
  "        logNow('[SET] speed=' + C.speed + (C.ready ? '' : ' (NOT ready)'));\n"
  "        if (C.ready) doSpeed();\n"
  "        return C.speed;\n"
  "      }\n"
  "      if (k === 'auto') {\n"
  "        C.auto = !!v;\n"
  "        logNow('[SET] auto=' + C.auto + (C.ready ? '' : ' (NOT ready)'));\n"
  "        return C.auto;\n"
  "      }\n"
  "      C[k] = !!v;\n"
  "      logNow('[SET] ' + k + '=' + C[k] + (C.ready ? '' : ' (NOT ready)'));\n"
  "      if (!C.ready) return C[k];             // ★ 未就绪：只记录，不操作\n"
  "      if (k === 'kill' && C.kill) doKill();\n"
  "      if (k === 'god') doGod();\n"
  "    } catch (e) { fail('set', e); }\n"
  "    return C[k];\n"
  "  };\n"
  "  C.probe = function () {\n"
  "    logNow('[PROBE] fc=' + (FC() ? 'Y' : 'N') + ' bBl=' + (BBl() ? 'Y' : 'N') +\n"
  "           ' nb=' + (NB() ? 'Y' : 'N') + ' ready=' + C.ready + ' tick=' + C._tickN + ' pump=' + C._pumpN);\n"
  "    return C.status();\n"
  "  };\n"
  "  C.status = function () {\n"
  "    return JSON.stringify({ ready: C.ready, kill: C.kill, god: C.god, speed: C.speed,\n"
  "                            auto: C.auto, err: C.err, tick: C._tickN, pump: C._pumpN });\n"
  "  };\n"
  "  window.warriorCheatSet = C.set;\n"
  "  window.warriorCheatProbe = C.probe;\n"
  "  window.warriorCheatStatus = C.status;\n"
  "\n"
  "  /* ---------------- 启动 ---------------- */\n"
  "  probeContext();\n"
  "  logNow('[OK] cheat v' + C.version + ' loaded, path=' + (window.__WR_PATH__ || '?'));\n"
  "  startDriver();\n"
  "  // 若 cc 尚不存在，稍后用 setInterval 重试启动驱动\n"
  "  var bootTry = 0;\n"
  "  var bootTimer = setInterval(function () {\n"
  "    bootTry++;\n"
  "    if (C._drvEvent) { clearInterval(bootTimer); return; }\n"
  "    if (typeof cc !== 'undefined') { startDriver(); }\n"
  "    if (bootTry > 40) { clearInterval(bootTimer); logNow('[!!] driver boot give up'); }\n"
  "  }, 500);\n"
  "})();\n"
  "\n"
  ;
#endif
